#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version = "2"

[[linters.exclusions.rules]]
linters = [ "errcheck" ]
source = "^\\s*defer\\s+" # don't flag deferred calls returning error
